### ISSUE TITLE
Add some language specifically excepting marketing versions, e.g. CSS3...

### ISSUE THREAD

**Issue by torgo** [w3ctag/the-web-is-not-versioned#1]
As discussed in today's call...

**Comment by jyasskin** [comment]
https://w3ctag.github.io/the-web-is-not-versioned/#the-web-platform-does-not-have-versions now has "Version numbers such as "Web 2.0" have been used for educational, communications or marketing purposes", which I think covers this. Feel free to re-open if I'm wrong.
